# Generated by Django 4.2.9 on 2026-04-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartamento"),
                            ("house", "Casa"),
                            ("commercial", "Comercial"),
                            ("land", "Terreno"),
                            ("rural", "Rural"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Imóvel",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "Venda"), ("rent", "Aluguel")],
                        default="sale",
                        max_length=10,
                        verbose_name="Tipo de Anúncio",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área em m²",
                        max_digits=8,
                        verbose_name="Área (m²)",
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Quartos"),
                ),
                (
                    "bathrooms",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Banheiros"
                    ),
                ),
                (
                    "parking_spots",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Vagas"),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Endereço")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "zipcode",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lido")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="properties.property",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="properties/%Y/%m/", verbose_name="Imagem"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Imagem Principal"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
                "ordering": ["order", "id"],
            },
        ),
    ]
